spring.application.name=exlibros

spring.datasource.url=jdbc:mariadb://localhost:3306/intercambio_libros
spring.datasource.username=testuser
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.generated-ddl=false
spring.jpa.hibernate.ddl-auto=none